custom_caption:
  path: data/custom_captions.json
dataset:
  captions_file: frankenstein_captions.json
  description: COCO-2017 dataset for image captioning
  download_url: https://www.kaggle.com/api/v1/datasets/download/awsaf49/coco-2017-dataset
  images_folder_name: coco2017/train2017
  name: COCO-2017
  output_folder_name: output
  zip_filename: coco-2017-dataset.zip
model:
  base_model_path: checkpoints/mobileclip_s0.pt
  checkpoint_dir: checkpoints
  device: cpu
  download_url: https://docs-assets.developer.apple.com/ml-research/datasets/mobileclip/mobileclip_s0.pt
  filename: mobileclip_s0.pt
  name: mobileclip_s0
project:
  root: /Users/erenyavuz/Desktop/KU/25 Spring/COMP447/Project/Repo/FlightVision
